### ISSUE TITLE
Weird behavior while calling applozicClient.getLatestMessages()

### ISSUE THREAD

**Issue by bm181354** [AppLozic/ApplozicSwift#138]
I'm testing Applozic SDK [Swift] for four things:
1. Message sent and received
2. Login
3. Getting latest  message.
4. Logout

For first two premises, SDK seems to working but for getting latest messages and logout. For getting latest messages,  I alway get message for old user i.e if I logout for user1 to User2. I still get `getLatestMessages()` of user1 instead of user2. However, If I sent message to those list. Users will received that as :
> user2 has sent the message--which is a desired behavior for sending messages.

Another observation:
i. This behavior goes away if I manual launch the application from Xcode if user is signed In.
ii. `applozicClient.logoutUser(...)` is not being called 
iii. Logout and laughing app from Xcode still shows the same behavior
iv. However, Login and re-launching app shows the correct messages from `applozicClient.getLatestMessages()`

Code Snippet: 

``` 
 func signOut(){
            print(ALUserDefaultsHandler.isLoggedIn()) // False everytime
            applozicClient.logoutUser { (err, response) in
            if err == nil{
                print("Succesfully logout")
                self.DEBUG_PRINT(msg: "Succesfully logout")
            }else{
                self.DEBUG_ALERT(msg: err?.localizedDescription ?? "Undefined error") // for UI tester
                self.DEBUG_PRINT(msg: err?.localizedDescription ?? "Undefined error") // for unit tester
            }
        }
    }
 ```
None of these are logs nor breakpoint is trigger.

```
 func getRecentMessage(completionHandler:@escaping ([ALMessage?]?,Any?)->()) {
        print(ALUserDefaultsHandler.isLoggedIn()) // alway true
        applozicClient.getLatestMessages(false, withCompletionHandler: { messageList, error in
            if error == nil {
                let messageList = messageList as? [ALMessage?] ?? [ALMessage?]()
                print("getRecentMessage no error")
                completionHandler(messageList,nil)
            }else{
                print("getRecentMessage error")
                completionHandler(nil,error)
            }
        })
    }
```
Can you tell what is going on here ?  I feel like some value is being persisted in as userDefault or some other local memory in device and giving these outcome. I have not implemented anything that store in local memory. The fact that even if I launch Xcode and it is having this problem means that there is some UserDefault or some other memory is screwing thing. I will really appreciate your help. I can provide you my entire custom Chat Manager implemented but I have very clearly followed the guideline while creating applozicClient.

**Comment by bm181354** [comment]
Found the error which is not mention in Applozic documentation for Custom UI:
I had to follow all the sample example for UI and found the code. This kind of things is what infuriate developers.  I wasted my whole day debugging following the documentation.
```
 func signOut(){
            let registerUserClientService: ALRegisterUserClientService = ALRegisterUserClientService()
            registerUserClientService.logout { (response, error) in
                if(error == nil && response?.status == "success") {
                    print("++log out")
                }
        }
    }
```

**Comment by mukeshthawani** [comment]
Thanks for sharing the details. Looks like a mistake from our side that we missed this call in the logout section.

We are in the process of updating the custom UI documentation and we’ll definitely improve it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
