### ISSUE TITLE
Update Kingfisher for Swift 

### ISSUE THREAD

**Issue by faraan** [AppLozic/ApplozicSwift#14]
Please update Kingfisher also for Swift 4 
I am getting error for Kingfisher 3.6..2 version
<img width="1277" alt="screen shot 2017-12-18 at 5 06 44 pm" src="https://user-images.githubusercontent.com/12351847/34104317-f603bd60-e415-11e7-8204-748c1042fba8.png">

**Comment by mukeshthawani** [comment]
Thanks for reporting. We will fix it in the next release.

**Comment by mukeshthawani** [comment]
Update Kingfisher to 3.13.1, it should fix the issue.
