### ISSUE TITLE
Fetching membersId from alChannelService.fetchChannel(clientChannelKey) returns nil

### ISSUE THREAD

**Issue by bm181354** [AppLozic/ApplozicSwift#146]
I'm working on group chat and want to get userId of people in a group/channel. I have invoked `alChannelService.fetchChannel(clientChannelKey)` which return ALChannel.
```
if let alChannel = alChannelService.fetchChannel(withClientChannelKey: clientChannelKey){
            // data has info
      completionHandler(true, alChannel)
}else{
            // data is nil
      completionHandler(false,nil)
 }
```
Output so far is bit underwhelming. 
Print out `print(alChannel.key)` -> provides me the actual key as desired
Print out `print(alChannel.clientChannelKey)` -> provides me the alChannel.clientChannelKey
In same vein name, adminKey all returns desired value but for everything else. 
I get nil returned for Applozic's server.

For instance:
`print(alChannel.membersName)` -> returns `nil`
`print(alChannel.groupUsers)` -> returns `nil` 

My algorithm that I'm working on heavily rely on knowing userIds of these users in the channel group.

**Comment by ShivamPokhriyal** [comment]
@bm181354 The method you are using doesn't give membersName.

You will have to use other method of ALChannelService ::
let channel = ALChannelService().getChannelByKey(Pass_Channel_Key_Here)
Here you will get channel.membersName and channel.membersId which are same.

**Comment by bm181354** [comment]
@ShivamPokhriyal  I appreciate the response. I will change the method immediately. I was just confused because it returns 'ALChannel' object which is what I needed. Clarify such things and removing redundant methods will be much appreciate from library further enhancing  your SDK.
