### ISSUE TITLE
UserDefaults erased?

### ISSUE THREAD

**Issue by JeremPlln** [AppLozic/ApplozicSwift#222]
Hello everyone, 

with the v2.7.0, my users are disconnected each time they kill their application. This problem only exists with the v2.7.0 . I tried the previous version v2.6.0 and v2.5.0 and I am not disconnect when I kill my application. 

Did you modify the code around the UserDefaults?

have a nice day :)

**Comment by mukeshthawani** [comment]
Thanks for sharing the information @JeremPlln 

We tried the sample app and, it seems to be working fine after we kill the app. Can you share more information to help us reproduce the issue? Like what do you mean by disconnection?

**Comment by JeremPlln** [comment]
Hi @mukeshthawani , 

sorry I am late in writting you back! it took me time to find the problem and finally found it! Nothing related to your `v2.7.0` and the problem appeared to be random. The origin was a call made too early in my lifecycle application. 

I close this issue, have a nice day!
