### ISSUE TITLE
Update Contact.

### ISSUE THREAD

**Issue by TechnoBrigadeInfotech** [AppLozic/ApplozicSwift#288]
i have found ALMessage property in andorid. This object has a property like _getcontact_ & _get channel_. I update **metadata** of this two object but in iOS how we set metadata of ALMessage property object.

**Comment by mukeshthawani** [comment]
You can check [this](https://docs.applozic.com/docs/ios-chat-message-api#section-send-message-with-metadata) docs section for sending a message with metadata in iOS.
