### ISSUE TITLE
Navigation bar disappears

### ISSUE THREAD

**Issue by yh2015** [AppLozic/ApplozicSwift#382]
Hello, when trying to launch chat with contact directly without going through the chat list, the navigation bar wont show up on the screen. Although the method should add the view to a navigation controller.

```
func launch(viewController: UIViewController, from vc: UIViewController) {
        let navVC = [ALKBaseNavigationViewController(rootViewController:]([url](url
)) viewController)
        guard vc.navigationController != nil else {
            vc.present(navVC, animated: true, completion: nil)
            return
        }
        vc.modalPresentationStyle = .fullScreen
        vc.navigationController?.pushViewController(viewController, animated: true)
    }
```
![screenshot](https://user-images.githubusercontent.com/29627069/109486588-bfb0a600-7a8b-11eb-9e88-d51f7cd909b0.jpeg)

**Comment by Sunilkumarr** [comment]
Hello @yh2015,

Can you share any sample project where you're getting this issue as I checked we have a navigation bar that will have a title and other options 
can you check are you using this below method for launching the one-to-one chat 

``launchChatWith(contactId: `` https://github.com/AppLozic/ApplozicSwift/blob/master/Demo/ApplozicSwiftDemo/ALChatManager.swift#L148

**Comment by yh2015** [comment]
Dear Sunil,

The issue is fixed now. Thanks for the support.


Thank you,

Yasser Hamdan
Software Engineer
____

Netvariant S.A.L., Hazmieh Square Center, Block A, 2nd Floor, Assayad Traffic Circle, Hazmieh, Lebanon.
T: +961 (5) 450934 | F: +961 (5) 450934 | W: www.netvariant.com<http://www.netvariant.com/>



From: Sunil Kumar ***@***.***>
Date: Thursday, March 25, 2021 at 10:51 AM
To: AppLozic/ApplozicSwift ***@***.***>
Cc: Yasser Hamdan ***@***.***>, Mention ***@***.***>
Subject: Re: [AppLozic/ApplozicSwift] Navigation bar disappears (#382)

Hello @yh2015<https://github.com/yh2015>,

Can you share any sample project where you're getting this issue as I checked we have a navigation bar that will have a title and other options
can you check are you using this below method for launching the one-to-one chat

launchChatWith(contactId: https://github.com/AppLozic/ApplozicSwift/blob/master/Demo/ApplozicSwiftDemo/ALChatManager.swift#L148
