### ISSUE TITLE
New Message Issue

### ISSUE THREAD

**Issue by mobileexpert1** [AppLozic/ApplozicSwift#387]
Messages did not receive in real-time I need to refresh the screen to show a new message

**Comment by Sunilkumarr** [comment]
@mobileexpert1 Hi,
Can you share the below details at support@applozic.com  :
1. Applozic application key and one login userId of applozic.
2. AppDelegate.swift file
3. Capture the complete logs from Xcode for the receiver phone and the sender phone.
