### ISSUE TITLE
Impossible to retrieve contacts

### ISSUE THREAD

**Issue by matteodanelli** [AppLozic/ApplozicSwift#4]
Hi, 
I found this library as a replacement for Framework inside swift project.
I see that Swift cocoapod is under development and maybe it's the reason of my problem.

With the sample provided I am not able to get contact list.

Any idea of the reason?

Thank you.

**Comment by mukeshthawani** [comment]
Thanks for giving it a try. Right now it only shows the contact with whom you have the conversation. 

We will add this feature in next version.

**Comment by mukeshthawani** [comment]
Fixed by #8
