### ISSUE TITLE
Xcode 13 "Cannot find 'CLLocationCoordinate2D' in scope"

### ISSUE THREAD

**Issue by appsstudioio** [AppLozic/ApplozicSwift#417]
Build error in Xcode 13

"ALMessage+Extension.swift:334:28: 
Cannot find 'CLLocationCoordinate2D' in scope"

**Comment by CripyIce** [comment]
Same here!

**Comment by Sunilkumarr** [comment]
@appsstudioio Hi, You can use the latest version [6.4.0](https://github.com/AppLozic/ApplozicSwift/releases/tag/6.4.0 ) this has been fixed.
