### ISSUE TITLE
Push Notifications don't receive at background and terminated state.

### ISSUE THREAD

**Issue by pyaephyoaung-pa** [AppLozic/ApplozicSwift#423]
I got Push Notification Testing message. But I do not receive from app chat message notification at background and terminated state
![Screenshot 2021-11-14 at 1 15 32 PM](https://user-images.githubusercontent.com/20982835/141670647-e145a7bd-1132-42a8-8cbd-2564148b7cc8.png)
.

**Comment by Sunilkumarr** [comment]
Hi @pyaephyoaung-pa,

Can you recheck if you have uploaded the **Apple Push Notification service SSL (Sandbox & Production)** .p12 file in both the Production and Development section on Applozic [console](https://console.applozic.com/login)? 

Docs for exporting and uploading the APNs p12 file [link](https://docs.applozic.com/docs/notifications-applozicswift#setting-up-apns-certificates
) 


If you still face the same issue you can share us your App-ID and login userId to support@applozic.com
