### ISSUE TITLE
Badge count doesn't display on iOS.

### ISSUE THREAD

**Issue by vivekshah-zymr** [AppLozic/ApplozicSwift#51]
I have integrated applozic pod in my project, I have set up the things as per the guide.
Now I am testing from iOS to iOS device, and receiving the push notifications in a proper way. But the badge count doesn't display.

The push notification format is as per below.
```
{
  "AL_KEY": "APPLOZIC_01",
  "AL_VALUE": {
    "id": "31c7f2b1a2e493e53c91bf650f9de55a3",
    "type": "APPLOZIC_01",
    "message": "vvk",
    "notifyUser": true,
    "totalUnreadCount": 1,
    "sendAlert": true,
    "messageMetaData": {}
  },
  "aps": {
    "alert": "DemoUserName: 1",
    "content-available": 1,
    "sound": "default"
  }
}
```
So push notification dictiorary itself doesn't contain badge parameter. I don't know if i missed something on setup or what. Please help me in this.

**Comment by mukeshthawani** [comment]
@vivekshah-zymr Yes, by default it won't come. Add below line in `defaultChatViewSettings` method in the ALChatManager file. After that reinstall the app and check.

`ALUserDefaultsHandler.setUnreadCountType(1)`
