### ISSUE TITLE
Provide a interface to handle title button tap on ALKConversationViewController

### ISSUE THREAD

**Issue by kbokdia** [AppLozic/ApplozicSwift#55]
**Feature Request**: Enable title button in ALKConversationViewController. And provide a interface to handle on title button tap. Or Atleast make title button open so that I could create CustomViewController which inherits ALKConversationViewController and write custom code on title button tap.

Applozic SDK version: 5.10.0

Xcode version: 9.4.1

iOS version: 11.4.1

**Comment by mukeshthawani** [comment]
@kbokdia I understand your use-case. I think it makes sense to add a way for you to override that. We will get it done in one of the next releases.

Thanks for sharing the details.

**Comment by ShivamPokhriyal** [comment]
Hello @kbokdia 

You can try our latest release 2.6.0. 
In case of 1-1 chat, you will get a notification with name UserProfileSelected. It will contain userId, display name and controller.
In case of group chat, we open group detail screen, there on tapping any participants, an activity sheet will open, we have added a hidden option "Info" which can be used to achieve your use-case. Detail of the same can be found on [this link](https://docs.applozic.com/docs/ios-swift-chat-theme-and-customization#section-show-info-option-in-group-detail-screen-).
