### ISSUE TITLE
Get the list of one-to-one chats only

### ISSUE THREAD

**Issue by najeeburrehman-brainx** [AppLozic/ApplozicSwift#59]
Is it possible to get the list of one-to-one chats only.
"ALMessageDBService" provides the list which includes all types of chats but I want the list of one-to-one chats and group chats separately.Is there anyway to do this...?

**Comment by Sunilkumarr** [comment]
As earlier we have shared the methods in mail and here also adding 
You can check this doc link for showing one to one or group chat latest messages  [link ](https://docs.applozic.com/v1.0/docs/ios-1-1-user-chat-and-group-chat#section-latest-messages-for-one-to-one-or-group-chats)
