### ISSUE TITLE
How to update Font family for all screens related to chat?

### ISSUE THREAD

**Issue by kbokdia** [AppLozic/ApplozicSwift#69]

**Comment by mukeshthawani** [comment]
Hi @kbokdia 

Currently, the font can be changed for individual labels like `message`, `displayName` etc.

https://github.com/AppLozic/ApplozicSwift/blob/511b12b58f8952ad9f62e066b6d58aa7de4630bd/Sources/Utilities/Message%2BStyle.swift#L12

You can call `ALKMessageStyle` and change it from any of your classes.
