### ISSUE TITLE
Is there any roaddmap to reduce warnings

### ISSUE THREAD

**Issue by rugmangathan** [AppLozic/ApplozicSwift#79]
Currently there are more than 187 warnings in the project.
<img width="283" alt="Xcode warnings" src="https://user-images.githubusercontent.com/8840399/46469863-4fd25e80-c7f2-11e8-9502-918dd0324672.png">

**Comment by mukeshthawani** [comment]
@rugmangathan Yes, we are working on it. The number of warnings will go down in the future releases.
