### ISSUE TITLE
I get error when I run the project in Xcode 10

### ISSUE THREAD

**Issue by kbokdia** [AppLozic/ApplozicSwift#82]
<img width="1422" alt="screen shot 2018-10-05 at 6 19 43 pm" src="https://user-images.githubusercontent.com/5452640/46536181-554fa780-c8cb-11e8-9f86-5b2f8c15039e.png">

**Comment by mukeshthawani** [comment]
Hi @kbokdia 

Thanks for sharing the details.
You can try the latest version `1.1.0`. This has been fixed.
